bundler_args: --retry 3
language: node_js
services:
  - mongodb
before_install:
 - export TZ=America/Chicago
 - npm install -g grunt-cli
install: npm install
before_script:
 - grunt
after_script:
 - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec
 - cat coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
notifications:
  on_failure: change
