bundler_args: --retry 3
language: node_js
node_js: 10
before_install:
 - export TZ=America/Chicago
 - npm install -g grunt-cli
install: npm install
before_script:
 - grunt
after_script:
 - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec --exit
notifications:
  on_failure: change
